services:
  - type: web
    name: focus-app-api
    env: node
    buildCommand: pnpm install && pnpm --filter=api run build
    startCommand: pnpm --filter=api run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: focus-app-web
    env: node
    buildCommand: pnpm install && pnpm --filter=web run build
    startCommand: pnpm --filter=web run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: ${focus-app-api.url}
