services:
  - type: web
    name: focus-app-api
    env: node
    buildCommand: pnpm install && pnpm --filter=api run build
    startCommand: pnpm --filter=api run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: ${focus-app-web.url}
      - key: BASE_URL
        value: ${focus-app-api.url}
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

  - type: web
    name: focus-app-web
    env: node
    buildCommand: pnpm install && pnpm --filter=web run build
    startCommand: pnpm --filter=web run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: ${focus-app-api.url}/api
